### ISSUE TITLE
Add a way to configure global settings

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/autometrics-rs#117]
@akesling brought up that you might want to configure autometrics settings via a config file or flags, rather than only environment variables.

If we wanted to support this, I can imagine two potential APIs for doing this:
1. Export an `init` or `SettingsBuilder` from the `autometrics` crate root. You would be able to set these settings only once and they would initialize a [`OnceCell`](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html) that would be used by all calls to the `#[autometrics]` macro.
2. Have an `autometrics::settings` module with setter methods for each setting we support. This would store the settings in a `RwLock`. Theoretically, you could set them at any time but it would be strongly recommended to set them before any metrics are actually collected.

So far, the use cases I can think of for these settings would be:
- Setting the `service.name` label, without relying on environment variables as @akesling suggested in https://github.com/autometrics-dev/autometrics-rs/pull/116#discussion_r1237205598
- Adding other labels to all metrics produced (we could potentially limit them to pairs of `&'static str`s if we want to guarantee that the feature is not used for anything that could be very high cardinality)
- Configuring the histogram buckets. Currently you cannot set the buckets when you're using the `prometheus` or `prometheus-client` crates, because they are set when the counters are initialized rather than on the exporter like for `opentelemetry` and `metrics`. This might be a minor issue but as a result, you [cannot use the `custom-objective-latencies` feature flag with the `prometheus` or `prometheus-client` crates](https://github.com/autometrics-dev/autometrics-rs/blob/66bab571166b245b2da98b90eb5c807dacadbc93/autometrics/src/objectives.rs#L213-L216). If we had an API for setting the buckets, you would be able to use these feature flags together.
- We could potentially allow users to control the functionality related to initializing the call counters to zero https://github.com/autometrics-dev/autometrics-rs/pull/119. We could keep the default behavior such that it's run on debug builds but you could also disable that if you want, or you could run it in release builds as well.
- Configuring the metrics registry #20 
- Maybe others?

Note that this would not be able to configure the `PROMETHEUS_URL` used to generate the links inserted into the docs, because that needs to be available at macro expansion time.

**Comment by emschwartz** [comment]
cc @autometrics-dev/rust-maintainers

**Comment by mies** [comment]
Out of curiosity; what are some of the tools or platforms people use to set service names currently?

**Comment by mellowagain** [comment]
having a global initialization function that gets called in a programs' `main` feels like the right way and is also the way other autometrics implementations like [autometrics-go](https://github.com/autometrics-dev/autometrics-go#import-the-libraries-and-initialize-the-metrics) do it.

the most rusty way would be ofcourse to configure per-proc-macro every time, in its arguments, but in the other pr u explained why thats a bad idea and i highkey agree so

**Comment by emschwartz** [comment]
> Adding other labels to all metrics produced (we could potentially limit them to pairs of &'static strs if we want to guarantee that the feature is not used for anything that could be very high cardinality)

I think we don't need to add this as a feature right now or potentially ever. If we allow you to pass in the registry (#20), you can set the labels on the registry itself.
