### ISSUE TITLE
Give better error message with `async_trait`

### ISSUE THREAD

**Issue by gagbo** [autometrics-dev/autometrics-rs#141]
`async_trait` is a popular macro to get around the limitation of asynchronous functions in trait definitions in Rust.

`autometrics` seems currently incompatible with _trait level_ annotations for `async_trait` traits; and currently gives an incoorect error message. This example comes fronm trying to add metrics to lemmy, which uses `async_trait` in the ActivityPub-related traits

```rust
#[autometrics::autometrics(objective = super::APUB_SLO)]
#[async_trait::async_trait]
impl ActivityHandler for DeleteUser {
  type DataType = LemmyContext;
  //...
```

won't work with a cryptic error message:

```console
error: expected `fn`
  --> crates/apub/src/activities/deletion/delete_user.rs:50:1
   |
50 | impl ActivityHandler for DeleteUser {
   | ^^^^

```

But adding the attribute to inner functions will work:

```rust
#[async_trait::async_trait]
impl ActivityHandler for DeleteUser {
  type DataType = LemmyContext;
  type Error = LemmyError;

  #[autometrics::autometrics(objective = super::APUB_SLO)]
  fn id(&self) -> &Url {
    &self.id
  }

  #[autometrics::autometrics(objective = super::APUB_SLO)]
  fn actor(&self) -> &Url {
    self.actor.inner()
  }

  #[autometrics::autometrics(objective = super::APUB_SLO)]
  async fn verify(&self, context: &Data<Self::DataType>) -> Result<(), LemmyError> {
    insert_received_activity(&self.id, context).await?;
    verify_is_public(&self.to, &[])?;
    verify_person(&self.actor, context).await?;
    verify_urls_match(self.actor.inner(), self.object.inner())?;
    Ok(())
  }

  #[autometrics::autometrics(objective = super::APUB_SLO)]
  async fn receive(self, context: &Data<Self::DataType>) -> Result<(), LemmyError> {
    let actor = self.actor.dereference(context).await?;
    if self.remove_data.unwrap_or(false) {
      purge_user_account(actor.id, context).await?;
    } else {
      Person::delete_account(&mut context.pool(), actor.id).await?;
    }
    Ok(())
  }
}

```

## Note

The issue might also come from the associated type in the trait now that I think about it, seeing the code. So adding an extra compilation test to make sure we can use `#[autometrics]` on trait implementation that have an associated type would also be welcome to remove that possible cause from the list of suspects.

**Comment by mellowagain** [comment]
ok so i was able to only reproduce this when `async_trait` is declared **after** `autometrics`. the other way around it doesnt happen

**Comment by gagbo** [comment]
I thought it was the case as well, but then I tried again and both orders failed for me in my memory. I wonder if there's an official ruling about the order of processing for attribute macros

**Comment by mellowagain** [comment]
i thought proc macros get invoked in the order theyre defined

**Comment by gagbo** [comment]
I guess it's the case for the time being, but it's not really specified https://github.com/rust-lang/reference/issues/578, so either I hit a caching issue or I forgot to save a file before compiling (probably the latter ngl)

**Comment by mellowagain** [comment]
i was tryign to see if we could maybe have a better error message by checking wheter the async-trait macro came after us but turns out you dont actually get the proc macros with your `input`. maybe any idea how else to achieve this?

else we might really just have to only define this behaviour in documentation and hope that users read that part of it

**Comment by gagbo** [comment]
I wonder what triggers the "expected fn" error in the first place. I think we can catch/rethrow the compilation error in autometrics code to hopefully insert a message about "Hey, did you try to instrument an implementation of an async trait? You should try swapping the attributes" or something

**Comment by mellowagain** [comment]
actually no i was mistaken, it gets passed to the proc macro, we just dont parse it correctly
