### ISSUE TITLE
Handling singint for telemetry http endpoint in a Tonic gRPC service?

### ISSUE THREAD

**Issue by marvin-hansen** [autometrics-dev/autometrics-rs#162]
Hi,

thanks for this great project, it really makes telemetry a lot easier. 

I'm porting currently a bunch of Golang services to Tokio/Rust while learning the Tokio/Tonic framework. I tried to add telemetry to one of my gRPC services, but bumped into an issue with handling sigint. Basically, without sigint, everything works just fine and I get the metrics straight into the dashboard. To make the service ready for Kubernetes deployment, a health and sigint handler is required so that k8s can manage the service correctly. 

The problem arises, when I add a signint handler to the tonic gRPC service, it is not clear to me how to add the same signal channel to the web server that exposes the metric.

Again, I am still learning all this stuff and might got a  few things wrong. 

However, I made a fully self-contained example based on one of the online tutorials that illustrates the point. 

Full code:  https://github.com/marvin-hansen/tonic-autometrics/blob/main/src/main.rs

The relevant section.

```rust 
    // Construct sigint signal handler for graceful shutdown
    let (signal_tx, signal_rx) = signal_channel();
    spawn(handle_sigterm(signal_tx));

    // Build gRPC server with health service and signal sigint handler
    let server = TonicServer::builder()
        .add_service(svc)
        .add_service(health_svc)
        .serve_with_shutdown(grpc_addr, async {
            signal_rx.await.ok();
        });

    // Start gRPC servedr
    // This one probably blocks the subsequent start of the web server. How do I start them either in Tandem?
    println!("Server listening on {}", grpc_addr);
    server
        .await
        .expect("Failed to start server");

    // Http handler that exposes metrics to Prometheus
    let app = Router::new().route("/", get(handler)).route(
        "/metrics",
        get(|| async { prometheus_exporter::encode_http_response() }),
    );

    // Web server with Axum
    // How do I add a graceful shutdown signal handler
    // that triggers a proper shutdown together with the gRPC server?
    axum::Server::bind(&web_addr)
        .serve(app.into_make_service())
        .await
        .expect("Web server failed");
```

Apparently, the Axum API doesn't have anything similar to the serve_with_shutdown method, but instead
[requires to construct a TCP listener that runs in an infinite loop waiting for a sigint signal.](https://github.com/tokio-rs/axum/blob/main/examples/graceful-shutdown/src/main.rs)

This seems a bit complicated to me and I just cannot figure out how to make the http server receive the same 
sigjnit as the gRPC server.

Repo with code:  https://github.com/marvin-hansen/tonic-autometrics/blob/main/src/main.rs

Any help is appreciated on this one.

**Comment by marvin-hansen** [comment]
Issue has been resolved with PR: https://github.com/autometrics-dev/autometrics-rs/pull/163

Please review. 

Thank you.

**Comment by gagbo** [comment]
Hello!

Yes, the whole graceful shutdown situation is something that needs to be solved outside of Autometrics as you figured out. Since the signal handler is supposed to kill the whole runtime it’s best left at the tokio level.

We're currently preparing a big release for autometrics, so we might not review the PR _just now_ but we will, thanks for it
