### ISSUE TITLE
Missing HTTP feature flag for opentelemetry-otlp

### ISSUE THREAD

**Issue by petehayes102** [autometrics-dev/autometrics-rs#169]
Hey, thanks for such an awesome project!

I followed the Rust Quickstart guide for OpenTelemetry, dropping this line into my Rust project:
```rust
otel_push_exporter::init_http("some_url")?; // Note the `?` is missing from your example
```

When I run my binary, the above line returns the following error:
> Error: Metrics exporter otlp failed with no http client, you must select one from features or provide your own implementation

I then tried to run your `example-opentelemetry-push` project, but it returned a similar error:
> Error: ExportErr(NoHttpClient)

I found that if I modified the "otel-push-exporter-http" feature in `./autometrics/Cargo.toml`, I could get it working:

```toml
otel-push-exporter-http = [
  "otel-push-exporter",
  "opentelemetry-otlp/http-proto",
  "opentelemetry-otlp/reqwest-client" # <-- new line
]
```

I'm happy to raise a PR but wasn't sure if maybe I'm missing something on my end? Instrumentation is a new subject for me.

**Comment by mellowagain** [comment]
yea good catch, thanks! feel free to support a pr. i think we should also use `opentelemetry-otlp/reqwest-rustls` so we do not depend on end users to have openssl installed
