### ISSUE TITLE
Support `AUTOMETRICS_DOCS_GEN=0` environment variable

### ISSUE THREAD

**Issue by arendjr** [autometrics-dev/autometrics-rs#80]
The purpose of this environment variable is to disable documentation generation by the macro. The VS Code extension would set this environment variable automatically in the Rust Analyzer settings, so that it becomes solely responsible for generating documentation tooltips.

This is a blocker for https://github.com/autometrics-dev/vscode-autometrics/issues/27

Feel free to suggest a better name still :sweat_smile:

**Comment by emschwartz** [comment]
Since it would only really check for the presence of the env var, I'm somewhat tempted to naming it `AUTOMETRICS_DISABLE_DOCS=1`. Any strong preference on that versus `AUTOMETRICS_DOCS_GEN`?

**Comment by arendjr** [comment]
You're right that might be a bit more idiomatic as far as env vars go :+1:
